package com.oepnske.rules;

/**
 * Assets Rules
 */

import com.openske.model.hardware.Host;
import com.openske.model.assets.Asset;
import com.openske.model.software.Software;
import com.openske.model.policy.PolicyState;

rule "Mark assets that reside on a vulnerable host or are connected to at least one vulnerable host"
    when
        $asset : Asset( $assetHost : host )
        exists(
            Software( host == $assetHost , policyState == PolicyState.RISKY )
            or
            (
                $connectedHost : Host( connections contains $assetHost )
                and
                Software( host == $connectedHost , policyState == PolicyState.RISKY )
            )
        )
    then
        $asset.setPolicyState(PolicyState.RISKY);
end
