#created on: Jun 11, 2010
package com.openske.rules;

#list any import classes here.

import com.openske.model.hardware.Host;
import com.openske.model.assets.Asset;


#declare any global variables here

rule "Validate that hosts have an address"
    when
	$host : Host(address == "")
    then
	retract($host);
end

rule "Indicate whether we don't have any assets"
    when
        not( Asset() )
    then
        System.out.println("\t - There are no assets defined till now");
end

