#!/bin/bash

OPENSKE_ROOT=$(dirname $0)
OPENSKE_CONSOLE=$OPENSKE_ROOT/openske-console
#MAVEN_OPTS="-Xms256m -Xmx512m"
MAVEN_BIN=mvn

function message() {
    echo -e ">> $1\n"
}

# Validate that Maven is installed

if [ -x "$MAVEN_BIN" ]; then
    echo "It seems Maven is either not installed or not in your PATH environment variable"
    exit 2
fi

# Clean and install all of OpenSKE's artifacts

message "Building OpenSKE..."

$MAVEN_BIN -q install -DskipTests

if [ $? == "0" ]; then

    message "Running OpenSKE's Console..."

    MAVEN_OPTS=$MAVEN_OPTS $MAVEN_BIN -q -f $OPENSKE_CONSOLE/pom.xml exec:java -Dexec.mainClass=openske.console.Console
fi
