package com.openske.rules;

/**
 * Software Rules
 */

import com.openske.model.software.Software;
import com.openske.model.policy.PolicyState;


rule "Mark any software with vulnerabilities or depends on vulnerable software as risky"
    when
        $software : Software( vulnerabilities.size > 0 )
        or
        (
            $riskyDependency : Software( policyState == PolicyState.RISKY )
            and
            $software : Software( dependencies contains $riskyDependency )
        )
    then
        $software.setPolicyState(PolicyState.RISKY);
end
