package openske.rules;

/**
 * Software Rules
 */

import openske.model.software.Software;
import openske.model.security.SecurityState;

import function openske.engine.Engine.print;

rule "Mark vulnerable software or others that depend on it as risky"
    when
        # Match any software that has vulnerabilities
        $sw : Software( vulnerabilities.size > 0 )
        or
        (
            # Match any previously identified risky software
            $dep : Software( securityState == SecurityState.RISKY )
            and
            # Check if any software depends on the matched risky one
            $sw : Software( dependencies contains $dep )
        )
    then
        print("[SOFTWARE] Setting " + $sw.toString() + " as risky since it has %d vulnerabilities", $sw.getVulnerabilities().size());
        $sw.setSecurityState(SecurityState.RISKY);
end
