package com.openske.rules

import com.openske.model.security.*;
import com.openske.model.software.*;
import com.openske.model.assets.*;

global java.io.PrintWriter output;

rule "Print assets that have become risky"
    when
        $asset : Asset( securityState == SecurityState.RISKY )
    then
        output.format("[LOGGING] Asset '" + $asset.getName() + "' has become risky !");
end


rule "Detect the presence of an attacker"
	when
		$attacker : User( attacker == true )
	then 
		output.format("[LOGGING] Attacker '%s' detected on host '%s'", $attacker.getFullName(), $attacker.getHost().getAddress()); 
end


rule "Detect the reachability of an attacker ( if any )"
    when
        $attacker : User( $attackerHost : host , attacker == true )
        $software : Software( $softwareHost : host )
        eval( $attackerHost.canReach($softwareHost) )
    then
        output.format("[LOGGING] Attacker '%s' can reach software '%s'", $attacker.getFullName(), $software.toString());
end
